FROM bioconductor/bioconductor_docker:RELEASE_3_17-R-4.3.0

# 1. Install system utilities and bedtools
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    bedtools \
    cmake \
    g++ \
    git \
    make \
    procps \
    sudo \
    unzip \
    wget \
    default-jre-headless \
    openjdk-11-jre \
    python3-dev \
    python3-pip \
    r-cran-ggplot2 \
    r-cran-optparse \
    python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 3. Global tool installations

# Handle dependency problems related to Java installation:
# https://stackoverflow.com/questions/61815233/install-java-runtime-in-debian-based-docker-image
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2

RUN mkdir -p /tmp

RUN mkdir -p /usr/local/lib/clusterone \
    && wget https://paccanarolab.org/static_content/clusterone/cluster_one-1.0.jar -O /usr/local/lib/clusterone/cluster_one-1.0.jar \
    && printf '#!/bin/bash\njava -jar /usr/local/lib/clusterone/cluster_one-1.0.jar "$@"\n' > /usr/local/bin/clusterone \
    && chmod +x /usr/local/bin/clusterone

RUN git clone https://github.com/TimGarrels/LazyFox /tmp/lazyfoxdir \
    && cd /tmp/lazyfoxdir && git reset --hard d08f3c084df19bd2a1726159f181bbe3ad6f5bf4 \
    && mkdir build && cd build && cmake .. && make \
    && mv LazyFox /usr/local/bin/LazyFox && chmod +x /usr/local/bin/LazyFox \
    && rm -rf /tmp/lazyfoxdir

# 4. Install Python & R dependencies
COPY dependencies/requirements-app.txt /tmp/requirements-app.txt
COPY dependencies/requirements-workflow.txt /tmp/requirements-workflow.txt
COPY dependencies/r-packages-workflow.sh /tmp/r-packages-workflow.sh

RUN pip3 install --no-cache-dir -r /tmp/requirements-app.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements-workflow.txt
RUN bash /tmp/r-packages-workflow.sh

RUN pip3 install --no-cache-dir git+https://github.com/fmfi-compbio/mcdp2.git@fd7c69f5e97db8c1052df859cb02d86533287e64

RUN rm -rf /tmp

WORKDIR /app